# Generated by Django 2.2.7 on 2021-09-07 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ashokapp', '0003_auto_20210907_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categorys',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ashokapp.Category'),
        ),
    ]
