# Generated by Django 2.2.7 on 2021-09-19 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ashokapp', '0006_auto_20210919_2257'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
