# Generated by Django 2.2.7 on 2021-09-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashokapp', '0009_auto_20210919_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
