# Generated by Django 2.2.7 on 2021-09-19 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ashokapp', '0010_auto_20210919_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
