# Generated by Django 2.2.7 on 2021-09-20 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ashokapp', '0011_remove_order_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
