# Generated by Django 2.2.7 on 2021-09-20 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ashokapp', '0014_auto_20210920_2037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
