# Generated by Django 2.2.7 on 2021-09-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashokapp', '0017_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
