# Generated by Django 3.1.7 on 2021-10-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashokapp', '0019_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=50)),
                ('dlname', models.CharField(max_length=60)),
                ('demail', models.EmailField(max_length=254)),
                ('dphone', models.IntegerField()),
                ('daddress', models.CharField(max_length=300)),
                ('dAadhaar', models.FileField(upload_to='pdf/')),
                ('dplant', models.CharField(max_length=100)),
                ('dcountplants', models.CharField(max_length=10)),
                ('dplantsimage', models.ImageField(upload_to='donateplantimage/')),
            ],
        ),
    ]
