# Generated by Django 3.1.7 on 2021-10-12 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ashokapp', '0020_donate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donate',
            old_name='dAadhaar',
            new_name='Aadhaar',
        ),
        migrations.RenameField(
            model_name='donate',
            old_name='daddress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='donate',
            old_name='dcountplants',
            new_name='countplants',
        ),
        migrations.RenameField(
            model_name='donate',
            old_name='demail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='donate',
            old_name='dlname',
            new_name='lname',
        ),
        migrations.RenameField(
            model_name='donate',
            old_name='dname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='donate',
            old_name='dphone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='donate',
            old_name='dplant',
            new_name='plant',
        ),
        migrations.RenameField(
            model_name='donate',
            old_name='dplantsimage',
            new_name='plantsimage',
        ),
    ]
