# Generated by Django 3.1.7 on 2021-10-12 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ashokapp', '0021_auto_20211012_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donate',
            name='Aadhaar',
        ),
        migrations.RemoveField(
            model_name='donate',
            name='plantsimage',
        ),
    ]
