# Generated by Django 3.1.7 on 2021-10-13 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ashokapp', '0022_auto_20211012_2300'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donate',
            new_name='donar',
        ),
    ]
