# Generated by Django 3.1.7 on 2021-10-13 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ashokapp', '0023_auto_20211013_0755'),
    ]

    operations = [
        migrations.DeleteModel(
            name='donar',
        ),
    ]
