# Generated by Django 3.1.7 on 2021-10-17 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ashokapp', '0026_auto_20211013_0831'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
