# Generated by Django 2.2.7 on 2021-10-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashokapp', '0028_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='donar',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
